### ISSUE TITLE
#Add Code of Conduct

### ISSUE THREAD

**Issue by KiranBaliga** [vanshchauhan21/CryptoTracker#1]
I would like to add code of conduct readme file to this project as a part of GSWOB24. Please let me know if it is okay to proceed.

**Comment by KiranBaliga** [comment]
I request to add <WOB> & <Level1> labels to this issue as a part of GSWOB'24 contribution. Thank you!

**Comment by KiranBaliga** [comment]
Please review the PR and provide feedback/review with appropriate labels. Thank you!

**Comment by mahenoorsalat** [comment]
I am willing to work on this repo . I have a strong foundation on front-End Technologies .. hope you can assign me this issues 

I am looking forward to your prompt reply 

Thank you :)

**Comment by KiranBaliga** [comment]
@mahenoorsalat I understand your will to contribute. But I have already raised a PR for this issue. Please request the author for a new assignment or raise a new issue altogether. Thank you for your understanding, friend.

**Comment by vanshchauhan21** [comment]
Good

**Comment by vanshchauhan21** [comment]
> I would like to add code of conduct readme file to this project as a part of GSWOB24. Please let me know if it is okay to proceed.

Yes you can add

**Comment by KiranBaliga** [comment]
@vanshchauhan21 Please review the PR addressed to this issue. Thank you!

**Comment by KiranBaliga** [comment]
Can you add the WOB24 and Level1 labels. It will be of great help!
