### ISSUE TITLE
[Feat]: add header in FAQ page

### ISSUE THREAD

**Issue by RachitSahu26** [vanshchauhan21/CryptoTracker#102]
The website currently does not have a disclaimer section, which is important for clarifying the terms and conditions under which the content is provided. To improve transparency and user trust, I propose adding a disclaimer link in the footer of the website.

Proposed Features:
Disclaimer Link: Add a link titled "Disclaimer" in the footer that directs users to a dedicated disclaimer page.
Content of the Disclaimer Page: This page should outline important information regarding the website's content, including any limitations of liability, general information about the services provided, and any other relevant legal disclaimers.
Visibility: Ensure that the disclaimer link is clearly visible and accessible from all pages of the website to comply with best practices for user information.

https://github.com/user-attachments/assets/79305646-8daf-47f1-9e47-54f188f14c38

**Comment by RachitSahu26** [comment]
If you assign me, I would love to work on this. Please assign this to me @vanshchauhan21

**Comment by vanshchauhan21** [comment]
> If you assign me, I would love to work on this. Please assign this to me @vanshchauhan21

Okay do it ☺️

**Comment by RachitSahu26** [comment]
![Screenshot (409)](https://github.com/user-attachments/assets/f0618686-6428-4cdc-90cf-dca15e793b00)

@vanshchauhan21
