### ISSUE TITLE
 Feature Request: Currency Converter Tool

### ISSUE THREAD

**Issue by sezallagwal** [vanshchauhan21/CryptoTracker#109]
## Overview
Add a Currency Converter tool to the CryptoTracker website that enables users to convert between various fiat currencies and cryptocurrencies in real-time. This feature will allow users to quickly see equivalent values across multiple currencies, enhancing the site's utility for global users.

## Purpose
To improve user experience by providing a convenient tool for currency conversion, allowing users to understand the value of cryptocurrencies in their preferred fiat currencies. This will aid users in making quick and informed financial decisions.

## Proposed Features
1. **Conversion Options**
   - Support for popular fiat currencies (e.g., USD, EUR, GBP, JPY, INR).
   - Support for major cryptocurrencies (e.g., BTC, ETH, LTC, etc.).
   - Option to add more currencies over time.

2. **Real-Time Exchange Rates**
   - Fetch real-time exchange rates from a reliable API (e.g., CoinGecko, CoinMarketCap, or OpenExchangeRates).
   - Automatically update rates periodically or allow users to refresh rates manually.

please assign this to me under `gssoc-ext`  `hacktoberfest` lables @vanshchauhan21

**Comment by vanshchauhan21** [comment]
> ## Overview
> Add a Currency Converter tool to the CryptoTracker website that enables users to convert between various fiat currencies and cryptocurrencies in real-time. This feature will allow users to quickly see equivalent values across multiple currencies, enhancing the site's utility for global users.
> 
> ## Purpose
> To improve user experience by providing a convenient tool for currency conversion, allowing users to understand the value of cryptocurrencies in their preferred fiat currencies. This will aid users in making quick and informed financial decisions.
> 
> ## Proposed Features
> 1. **Conversion Options**
>    
>    * Support for popular fiat currencies (e.g., USD, EUR, GBP, JPY, INR).
>    * Support for major cryptocurrencies (e.g., BTC, ETH, LTC, etc.).
>    * Option to add more currencies over time.
> 2. **Real-Time Exchange Rates**
>    
>    * Fetch real-time exchange rates from a reliable API (e.g., CoinGecko, CoinMarketCap, or OpenExchangeRates).
>    * Automatically update rates periodically or allow users to refresh rates manually.
> 
> please assign this to me under `gssoc-ext` `hacktoberfest` lables @vanshchauhan21

Oky
