### ISSUE TITLE
Wrong text color in dark mode

### ISSUE THREAD

**Issue by RushilJalal** [vanshchauhan21/CryptoTracker#110]
![image](https://github.com/user-attachments/assets/742bbf4c-88c6-4f20-ab0b-b1dd0130bd82)

I would like to work on this issue.

**Comment by vanshchauhan21** [comment]
> ![image](https://private-user-images.githubusercontent.com/54212357/380423678-742bbf4c-88c6-4f20-ab0b-b1dd0130bd82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NTMxODAsIm5iZiI6MTcyOTk1Mjg4MCwicGF0aCI6Ii81NDIxMjM1Ny8zODA0MjM2NzgtNzQyYmJmNGMtODhjNi00ZjIwLWFiMGItYjFkZDAxMzBiZDgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDE0MjgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNzk2NmQyZTEyMDA2MzI1NzBjNTk3NjEyMjIzYTgyOTRhY2Y2Zjk2YzM0MGI2NmYyZjE4NDQxYWMxZTM5OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4Wc0Glt1n8Yzi_BpM_h9lbVoK4zTRhVLHCMubW6Ro3w)
> 
> I would like to work on this issue.

Okay bro do it

**Comment by sezallagwal** [comment]
@RushilJalal This issue was assigned to me #88
@vanshchauhan21 Can you close this issue

**Comment by vanshchauhan21** [comment]
> @RushilJalal This issue was assigned to me #88 @vanshchauhan21 Can you close this issue

Oky bro
