### ISSUE TITLE
Add Multi-Language Support Using Language Translator

### ISSUE THREAD

**Issue by TBorundia** [vanshchauhan21/CryptoTracker#115]
Implement a language translation API to allow dynamic switching between multiple languages.
Add a language selector (dropdown or buttons) to the UI for easy language switching.

**Comment by vanshchauhan21** [comment]
> Implement a language translation API to allow dynamic switching between multiple languages. Add a language selector (dropdown or buttons) to the UI for easy language switching.

Great 👍

**Comment by TBorundia** [comment]
@vanshchauhan21 ,
Can you please help me with this. The project is not displaying in my local device.
![image](https://github.com/user-attachments/assets/f482ac3e-8f45-4452-86bb-aed8f4d37451)

**Comment by vanshchauhan21** [comment]
> @vanshchauhan21 , Can you please help me with this. The project is not displaying in my local device. ![image](https://private-user-images.githubusercontent.com/168854094/380491179-f482ac3e-8f45-4452-86bb-aed8f4d37451.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMzQ4MzMsIm5iZiI6MTczMDAzNDUzMywicGF0aCI6Ii8xNjg4NTQwOTQvMzgwNDkxMTc5LWY0ODJhYzNlLThmNDUtNDQ1Mi04NmJiLWFlZDhmNGQzNzQ1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QxMzA4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzllNzkxYzJiMjRkMDcwNzY4MjgwMTcxNDFiMjMzZDdlODFmNmZjNTdjNmFkNzQ1MTk2MjllZjNiNGQxNDZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZLAh6fJ6WrAIJESHi2K5i_8N1Wcqp2jqhHGnWsFPxRw)

You need to re clone the repository then run the project,
Because I made the some changes
