### ISSUE TITLE
Adding feedback form

### ISSUE THREAD

**Issue by TBorundia** [vanshchauhan21/CryptoTracker#116]
Create a feedback form to collect user input and improve website features. The form should include the following:

Input fields for name, email, and feedback message.
A star rating system for user satisfaction.
Form validation to ensure all fields are correctly filled before submission.
A responsive design that works seamlessly on all devices.
A success/failure message after form submission.

**Comment by vanshchauhan21** [comment]
> Create a feedback form to collect user input and improve website features. The form should include the following:
> 
> Input fields for name, email, and feedback message. A star rating system for user satisfaction. Form validation to ensure all fields are correctly filled before submission. A responsive design that works seamlessly on all devices. A success/failure message after form submission.

Oky you can do it 👍
