### ISSUE TITLE
Feat: Add colored borders in list just like grid section under dashboard

### ISSUE THREAD

**Issue by Irtesaam** [vanshchauhan21/CryptoTracker#119]
The green & red colored borders to depict profit and loss in grid section is really good. I want to extend this feature to list section as well.

https://github.com/user-attachments/assets/cad4b5d8-467c-4bfe-b40a-df4a213f6cee

Please assign me this with label WoB24, GSSoC-ext24 and Hacktoberfest24.

**Comment by vanshchauhan21** [comment]
> The green & red colored borders to depict profit and loss in grid section is really good. I want to extend this feature to list section as well.
> 
>  Screencast.from.2024-10-28.02-26-45.mp4 
> Please assign me this with label WoB24, GSSoC-ext24 and Hacktoberfest24.

Okay bro I will assign you do it
