### ISSUE TITLE
Enhancement of  Dashboard Page

### ISSUE THREAD

**Issue by Shariq2003** [vanshchauhan21/CryptoTracker#12]
I will enhance the dashboard page by improving the cards' styling in the grid and list layouts. Additionally, I will update the pagination styling to create a more visually appealing and user-friendly interface.

Tasks:

1. Card Styling Enhancements:
- Improve the design of cards in grid layout to ensure consistency and better readability.
- Redesign the list layout cards for improved aesthetics and user experience.

2. Pagination Styling Update:
- Redesign the pagination component to be more visually appealing and user-friendly.

https://github.com/user-attachments/assets/1bbd38bc-fb1e-4c9b-bc9b-4ca4b96cf9c9

@vanshchauhan21 Please assign this to me under GSSOC Ext.

**Comment by Shariq2003** [comment]
@vanshchauhan21 also assign this to me.

**Comment by Shariq2003** [comment]
@vanshchauhan21 please assign this to me.

**Comment by vanshchauhan21** [comment]
> @vanshchauhan21 sir, please assign this to me. and also please add label of level and also gssoc-ext label

Okay 👍

**Comment by Shariq2003** [comment]
@vanshchauhan21 sir, you have unassigned me.

**Comment by vanshchauhan21** [comment]
> @vanshchauhan21 sir, you have unassigned me.

Ops sorry by mistake
