### ISSUE TITLE
Pull Request Issue checker workflow🚀

### ISSUE THREAD

**Issue by amiya-cyber** [vanshchauhan21/CryptoTracker#127]
Description: We need to create a GitHub Actions workflow that automates the validation of pull requests (PRs). This workflow will ensure that all PRs meet the following criteria before being merged:

PR Description Check: Every PR must have a description. If the description is missing, the PR should fail the check.

Acceptance Criteria:

A GitHub Action workflow is triggered on PR events (opened, edited).

The workflow checks the PR body for:

A non-empty description.
The presence of Fixes # or Fixes #NEW.
If the criteria are not met:

The workflow should fail and return clear error messages.
If the checks pass:

A confirmation message is outputted.

please @vanshchauhan21 assign this with level 3 label

**Comment by amiya-cyber** [comment]
can you please @vanshchauhan21 assign me this issue

**Comment by vanshchauhan21** [comment]
> can you please @vanshchauhan21 assign me this issue

Done bro 👍
