### ISSUE TITLE
Feature: Create Separate Disclaimer Page 

### ISSUE THREAD

**Issue by RachitSahu26** [vanshchauhan21/CryptoTracker#151]
Is your feature request related to a problem? Please describe.
Currently, the site lacks a dedicated Disclaimer page, which may leave users without clear information about the site's legal disclaimers, limitations of liability, or usage terms. Having all relevant disclaimers in one place ensures transparency and legal clarity.

@vanshchauhan21 

![Screenshot (417)](https://github.com/user-attachments/assets/1789a120-032f-4821-a8c7-f19dda77be16)

**Comment by RachitSahu26** [comment]
i Would like to work on it @vanshchauhan21

**Comment by vanshchauhan21** [comment]
> i Would like to work on it @vanshchauhan21

Oky do it
