### ISSUE TITLE
[Feature]: Implement Carousel Card to Showcase Why Users Love Our Website

### ISSUE THREAD

**Issue by RachitSahu26** [vanshchauhan21/CryptoTracker#153]
Is your feature request related to a problem? Please describe.
Currently, there is no engaging way to display customer feedback or the reasons why users love our website. A static text block doesn't capture users' attention effectively, missing the chance to highlight testimonials and key features dynamically.

![Screenshot (420)](https://github.com/user-attachments/assets/427ac0e5-f0df-4717-ac2a-c0aa5e4f69bd)

i would like to work on it @vanshchauhan21

**Comment by vanshchauhan21** [comment]
> Is your feature request related to a problem? Please describe. Currently, there is no engaging way to display customer feedback or the reasons why users love our website. A static text block doesn't capture users' attention effectively, missing the chance to highlight testimonials and key features dynamically.
> 
> ![Screenshot (420)](https://private-user-images.githubusercontent.com/129506267/380873550-427ac0e5-f0df-4717-ac2a-c0aa5e4f69bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNzk2OTYsIm5iZiI6MTczMDE3OTM5NiwicGF0aCI6Ii8xMjk1MDYyNjcvMzgwODczNTUwLTQyN2FjMGU1LWYwZGYtNDcxNy1hYzJhLWMwYWE1ZTRmNjliZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQwNTIzMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDM5MzFhMTJkODgzOTVhZDZkNmEyMGQzOWUzM2FmZjU2OWQ1YWEzYTc3OTBjODZhZGE0ZDRiN2I1YTRlY2UyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.D-pYU2MTNUrLnwZxFJzg5aQ0U1EodMll_VJo_5wJiGw)
> 
> i would like to work on it @vanshchauhan21

Oky do it
