### ISSUE TITLE
Redesign Contributor Card to Align with Project Theme

### ISSUE THREAD

**Issue by Priyanshi0112** [vanshchauhan21/CryptoTracker#166]
The current design of the contributor cards on the Contributors page does not align with the overall theme of the project, leading to a disjointed user experience. The existing card design lacks visual cohesion and fails to effectively represent the branding and aesthetic principles established throughout the application.

![image](https://github.com/user-attachments/assets/d5d47ccf-aafe-424f-ae44-2d5802e1ba38)

**Comment by vanshchauhan21** [comment]
> The current design of the contributor cards on the Contributors page does not align with the overall theme of the project, leading to a disjointed user experience. The existing card design lacks visual cohesion and fails to effectively represent the branding and aesthetic principles established throughout the application.
> 
> ![image](https://private-user-images.githubusercontent.com/137524681/381006346-d5d47ccf-aafe-424f-ae44-2d5802e1ba38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTE2MjEsIm5iZiI6MTczMDE5MTMyMSwicGF0aCI6Ii8xMzc1MjQ2ODEvMzgxMDA2MzQ2LWQ1ZDQ3Y2NmLWFhZmUtNDI0Zi1hZTQ0LTJkNTgwMmUxYmEzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQwODQyMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjQ0MGQ4MjI2NzEwYjM0M2M0N2Q0NGZhOGM3ODQxNDBhNTZlNjVmNWFmMzk4NTIxMDY5MDUzNzVlZTk4NGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3trlFsgFABpTbkxpXFIYWiIU9Yl_9Xb4Ybp4spcLTjQ)

Oky design it
