### ISSUE TITLE
Lack of Spacing Between Navbar and Search Box

### ISSUE THREAD

**Issue by Priyanshi0112** [vanshchauhan21/CryptoTracker#168]
The current layout of the website presents an issue where there is no spacing between the navigation bar (navbar) and the search box. This lack of spacing creates a visually cluttered appearance, making it difficult for users to distinguish between the two elements.

![image](https://github.com/user-attachments/assets/e46b9fbe-1c61-4f45-85da-3d01ec5b3adb)

**Comment by vanshchauhan21** [comment]
> The current layout of the website presents an issue where there is no spacing between the navigation bar (navbar) and the search box. This lack of spacing creates a visually cluttered appearance, making it difficult for users to distinguish between the two elements.
> 
> ![image](https://private-user-images.githubusercontent.com/137524681/381014281-e46b9fbe-1c61-4f45-85da-3d01ec5b3adb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTE1ODQsIm5iZiI6MTczMDE5MTI4NCwicGF0aCI6Ii8xMzc1MjQ2ODEvMzgxMDE0MjgxLWU0NmI5ZmJlLTFjNjEtNGY0NS04NWRhLTNkMDFlYzViM2FkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQwODQxMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGVlNjZhNjIzNWJhNWFiNGQ1ZWQ0NTVlOTQ3NjE5NDc3ZjM3OWZkZjUzNTY1MjA3YzBlZWMxOTQxM2ZiYzMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wRjSDPcuTUKWcWC5TWOfT4PHklaVnvj9zhqEsLr6uQQ)

Oky do it
