### ISSUE TITLE
Add more Links and Improve Entire Footer

### ISSUE THREAD

**Issue by RachitSahu26** [vanshchauhan21/CryptoTracker#175]
![Screenshot (422)](https://github.com/user-attachments/assets/48162451-f017-4cff-bee6-0e211f92fbba)

like this 
  @vanshchauhan21

**Comment by RachitSahu26** [comment]
I have completed this check it then i will send PR @vanshchauhan21

**Comment by vanshchauhan21** [comment]
> I have completed this check it then i will send PR @vanshchauhan21

Where?

**Comment by RachitSahu26** [comment]
> > I have completed this check it then i will send PR @vanshchauhan21
> 
> Where?

add Label i am waiting @vanshchauhan21

**Comment by vanshchauhan21** [comment]
> > > I have completed this check it then i will send PR @vanshchauhan21
> > 
> > 
> > Where?
> 
> add Label i am waiting @vanshchauhan21

Added
