### ISSUE TITLE
Improving Readability: Adjusting Pricing Text Color 

### ISSUE THREAD

**Issue by Priyanshi0112** [vanshchauhan21/CryptoTracker#177]
The color of the pricing text is not sufficiently visible in both light and dark modes, resulting in readability issues.

https://github.com/user-attachments/assets/8cb8e8d4-6821-4536-b1f5-9be4a51be073

**Comment by vanshchauhan21** [comment]
> The color of the pricing text is not sufficiently visible in both light and dark modes, resulting in readability issues.
> 
>  price.mp4

Oky do it
