### ISSUE TITLE
BUG : Landing page issue in dark mode

### ISSUE THREAD

**Issue by Irtesaam** [vanshchauhan21/CryptoTracker#179]
The landing page is not properly behaving in dark mode. The navbar changes color but the page doesn't.

![image](https://github.com/user-attachments/assets/7d54df35-8e4e-4df7-8391-f231c7f3b0f8)

Please assign it under WoB, GSSoC and Hacktoberfest

**Comment by vanshchauhan21** [comment]
> The landing page is not properly behaving in dark mode. The navbar changes color but the page doesn't.
> 
> ![image](https://private-user-images.githubusercontent.com/96732970/381079449-7d54df35-8e4e-4df7-8391-f231c7f3b0f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTc5NzAsIm5iZiI6MTczMDE5NzY3MCwicGF0aCI6Ii85NjczMjk3MC8zODEwNzk0NDktN2Q1NGRmMzUtOGU0ZS00ZGY3LTgzOTEtZjIzMWM3ZjNiMGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDEwMjc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlMTRiZDhkZGM2MjYxMzM1YzRmYWVhNWFhOGFiYTFiOWYwNDg1NTQ4NGVhY2ViMTM4ZWJlMzQxZGMwYWYyYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mub4ovTOvRk0zQ10hpMcx6a4dUu98VMaE3XKdEyrDYE)
> 
> Please assign it under WoB, GSSoC and Hacktoberfest

Oky do it
