### ISSUE TITLE
 Adding Animation to Contributor Cards on the Contributors Page

### ISSUE THREAD

**Issue by Priyanshi0112** [vanshchauhan21/CryptoTracker#188]
The current design of contributor cards on the Contributors page lacks animation, resulting in a static and less engaging user experience. Adding animations to these cards will improve interactivity, making the page feel more dynamic and visually appealing. This enhancement will draw attention to each contributor, creating a more immersive experience that aligns with the modern and interactive aesthetic of the project. The animations should be subtle to ensure they enhance rather than distract from the page’s content.

**Comment by vanshchauhan21** [comment]
> The current design of contributor cards on the Contributors page lacks animation, resulting in a static and less engaging user experience. Adding animations to these cards will improve interactivity, making the page feel more dynamic and visually appealing. This enhancement will draw attention to each contributor, creating a more immersive experience that aligns with the modern and interactive aesthetic of the project. The animations should be subtle to ensure they enhance rather than distract from the page’s content.

Oky do it 👍
