### ISSUE TITLE
Real time is not visible in dark mode 

### ISSUE THREAD

**Issue by Priyanshi0112** [vanshchauhan21/CryptoTracker#192]
The "Real Time" text on the home page is not clearly visible in dark mode, causing readability issues. The current color does not provide sufficient contrast against the dark background, making the text difficult to see and diminishing user experience. Adjusting the color or contrast for dark mode will ensure that "Real Time" remains prominent and accessible across all display modes.

![image](https://github.com/user-attachments/assets/e6fe6a7f-a01a-42a6-a8dd-5730827cf97f)

**Comment by vanshchauhan21** [comment]
> The "Real Time" text on the home page is not clearly visible in dark mode, causing readability issues. The current color does not provide sufficient contrast against the dark background, making the text difficult to see and diminishing user experience. Adjusting the color or contrast for dark mode will ensure that "Real Time" remains prominent and accessible across all display modes.
> 
> ![image](https://private-user-images.githubusercontent.com/137524681/381157688-e6fe6a7f-a01a-42a6-a8dd-5730827cf97f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMTMwNTEsIm5iZiI6MTczMDIxMjc1MSwicGF0aCI6Ii8xMzc1MjQ2ODEvMzgxMTU3Njg4LWU2ZmU2YTdmLWEwMWEtNDJhNi1hOGRkLTU3MzA4MjdjZjk3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxNDM5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTZlNTY1MmFjYTVkMjU5ZWJhYzRiZDIxMmVhMGQ1N2YzNTY1NmE5ZGIyNmU4NDdlN2ZhYjE5MzY0NTI1NjYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AG5yW39Ux_zxxhMhaVDEFjIcmcsCIwZiwpx6vlWSI64)

Oky do it
