### ISSUE TITLE
Correcting Newsletter alignment in footer

### ISSUE THREAD

**Issue by Priyanshi0112** [vanshchauhan21/CryptoTracker#195]
The headline newsletter its content and it subscribe button everything is scattered 

![image](https://github.com/user-attachments/assets/aa513055-5896-467b-a72e-803fe59cd1dc)

**Comment by vanshchauhan21** [comment]
> The headline newsletter its content and it subscribe button everything is scattered
> 
> ![image](https://private-user-images.githubusercontent.com/137524681/381185647-aa513055-5896-467b-a72e-803fe59cd1dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMTU3MDYsIm5iZiI6MTczMDIxNTQwNiwicGF0aCI6Ii8xMzc1MjQ2ODEvMzgxMTg1NjQ3LWFhNTEzMDU1LTU4OTYtNDY3Yi1hNzJlLTgwM2ZlNTljZDFkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxNTIzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjgzYTI0ZDJkMDY1Yzg0MmEyODNkOTUxYzlkNmUwZTRjMGU4NTRiYjRmZDEwNGMxMmNlNDNmNDNiNzEwZDJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.anV0rmaSiqP1GFmcNwEAwGcFtJ7dRz12FhOuugejQfM)

Do it
