### ISSUE TITLE
 Progress Bar for Enhanced User Experience

### ISSUE THREAD

**Issue by Priyanshi0112** [vanshchauhan21/CryptoTracker#196]
To improve user experience, a progress bar is requested for the website. This feature will visually indicate the user's scroll or load progress, providing immediate feedback and enhancing navigation. The progress bar could appear at the top or side of the screen, smoothly updating as users scroll through pages or load content, helping them track their location within the content and improve overall usability.

**Comment by vanshchauhan21** [comment]
> To improve user experience, a progress bar is requested for the website. This feature will visually indicate the user's scroll or load progress, providing immediate feedback and enhancing navigation. The progress bar could appear at the top or side of the screen, smoothly updating as users scroll through pages or load content, helping them track their location within the content and improve overall usability.

Do it
