### ISSUE TITLE
Dark mode is not working on Learn page 

### ISSUE THREAD

**Issue by Priyanshi0112** [vanshchauhan21/CryptoTracker#199]
Dark mode is not working on learn page 

![image](https://github.com/user-attachments/assets/fe3d495c-9897-424f-89e8-4515d9424bdf)

**Comment by vanshchauhan21** [comment]
> Dark mode is not working on learn page
> 
> ![image](https://private-user-images.githubusercontent.com/137524681/381207971-fe3d495c-9897-424f-89e8-4515d9424bdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjM3NDEsIm5iZiI6MTczMDIyMzQ0MSwicGF0aCI6Ii8xMzc1MjQ2ODEvMzgxMjA3OTcxLWZlM2Q0OTVjLTk4OTctNDI0Zi04OWU4LTQ1MTVkOTQyNGJkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxNzM3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGU5YjAwYTMyNmZhZGFiYWMzMjg0ZjU4ODhmNDk3MTM0ZTQ2N2FjMzI3ZDljMTBmYjI5ZTkxYzI3ZjUwZGZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zDqAN4MfiBMsvxgMBsQdFj1y1hLw7RpMp0LDCA3wNI4)



> Dark mode is not working on learn page
> 
> ![image](https://private-user-images.githubusercontent.com/137524681/381207971-fe3d495c-9897-424f-89e8-4515d9424bdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjM3NDEsIm5iZiI6MTczMDIyMzQ0MSwicGF0aCI6Ii8xMzc1MjQ2ODEvMzgxMjA3OTcxLWZlM2Q0OTVjLTk4OTctNDI0Zi04OWU4LTQ1MTVkOTQyNGJkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxNzM3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGU5YjAwYTMyNmZhZGFiYWMzMjg0ZjU4ODhmNDk3MTM0ZTQ2N2FjMzI3ZDljMTBmYjI5ZTkxYzI3ZjUwZGZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zDqAN4MfiBMsvxgMBsQdFj1y1hLw7RpMp0LDCA3wNI4)



> Dark mode is not working on learn page
> 
> ![image](https://private-user-images.githubusercontent.com/137524681/381207971-fe3d495c-9897-424f-89e8-4515d9424bdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjM3NDEsIm5iZiI6MTczMDIyMzQ0MSwicGF0aCI6Ii8xMzc1MjQ2ODEvMzgxMjA3OTcxLWZlM2Q0OTVjLTk4OTctNDI0Zi04OWU4LTQ1MTVkOTQyNGJkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxNzM3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGU5YjAwYTMyNmZhZGFiYWMzMjg0ZjU4ODhmNDk3MTM0ZTQ2N2FjMzI3ZDljMTBmYjI5ZTkxYzI3ZjUwZGZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zDqAN4MfiBMsvxgMBsQdFj1y1hLw7RpMp0LDCA3wNI4)

Oky do it
