### ISSUE TITLE
Feature Request: Implement Crypto Converter Functionality

### ISSUE THREAD

**Issue by RachitSahu26** [vanshchauhan21/CryptoTracker#200]
Summary:
Request to develop a Crypto Converter feature that allows users to convert between different cryptocurrencies seamlessly.

Motivation:
Many users need to quickly convert one cryptocurrency to another based on current exchange rates. This feature will enhance user experience by providing a simple and efficient way to perform conversions without needing to use external tools.

![Screenshot (427)](https://github.com/user-attachments/assets/0dc7c8bf-2d30-44b3-8bc3-5e1d55a4b265)

i would like to work on it @vanshchauhan21

**Comment by vanshchauhan21** [comment]
> Summary: Request to develop a Crypto Converter feature that allows users to convert between different cryptocurrencies seamlessly.
> 
> Motivation: Many users need to quickly convert one cryptocurrency to another based on current exchange rates. This feature will enhance user experience by providing a simple and efficient way to perform conversions without needing to use external tools.
> 
> ![Screenshot (427)](https://private-user-images.githubusercontent.com/129506267/381210460-0dc7c8bf-2d30-44b3-8bc3-5e1d55a4b265.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjM1OTksIm5iZiI6MTczMDIyMzI5OSwicGF0aCI6Ii8xMjk1MDYyNjcvMzgxMjEwNDYwLTBkYzdjOGJmLTJkMzAtNDRiMy04YmMzLTVlMWQ1NWE0YjI2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxNzM0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTcxZmI2MGMyMzNiNmE3YWUzZTljOTE3YjYyNzEzZTMyZmUyOWU5ZGMyMTIxYTVlMmJjNmM5MWFhOTllNGYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1GdA-Ap3YDOUqmO9bY2fbKIqUl8dhqAI9RgKQupEZgk)
> 
> i would like to work on it @vanshchauhan21

Oky do it
