### ISSUE TITLE
Feature Request: Implement Cookie Privacy Policy and Management

### ISSUE THREAD

**Issue by RachitSahu26** [vanshchauhan21/CryptoTracker#202]
Request to develop a Cookie Privacy feature that informs users about the cookies used on the Crypto Tracker platform and provides options for managing cookie preferences.

Motivation:
As privacy regulations (like GDPR) require transparency about cookie usage, implementing a Cookie Privacy feature will help ensure compliance and enhance user trust.

https://github.com/user-attachments/assets/f62e98b8-0d9e-4233-8d52-64d901fc4ecf

i would like to work on it @vanshchauhan21

**Comment by vanshchauhan21** [comment]
> Request to develop a Cookie Privacy feature that informs users about the cookies used on the Crypto Tracker platform and provides options for managing cookie preferences.
> 
> Motivation: As privacy regulations (like GDPR) require transparency about cookie usage, implementing a Cookie Privacy feature will help ensure compliance and enhance user trust.
> 
>  cookie.mp4 
> i would like to work on it @vanshchauhan21

Oky do it
