### ISSUE TITLE
Improve Privacy Policy Content Visibility in Dark Mode

### ISSUE THREAD

**Issue by Priyanshi0112** [vanshchauhan21/CryptoTracker#203]
In Dark Mode, certain sections of the Privacy Policy content are difficult to read due to low contrast with the background. This impacts readability and accessibility, making it challenging for users to access important information. Adjusting the color or background for Dark Mode will enhance visibility and ensure a consistent experience across display modes.

![image](https://github.com/user-attachments/assets/9213adee-5ebb-4f1a-a20d-5dd30e4d5934)

**Comment by vanshchauhan21** [comment]
> In Dark Mode, certain sections of the Privacy Policy content are difficult to read due to low contrast with the background. This impacts readability and accessibility, making it challenging for users to access important information. Adjusting the color or background for Dark Mode will enhance visibility and ensure a consistent experience across display modes.
> 
> ![image](https://private-user-images.githubusercontent.com/137524681/381212930-9213adee-5ebb-4f1a-a20d-5dd30e4d5934.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjM1MjYsIm5iZiI6MTczMDIyMzIyNiwicGF0aCI6Ii8xMzc1MjQ2ODEvMzgxMjEyOTMwLTkyMTNhZGVlLTVlYmItNGYxYS1hMjBkLTVkZDMwZTRkNTkzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQxNzMzNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzQwNjBlODA4ZWNhNzNmYWZhYzEwMTAzOTE3OTFkMWYwMDNmYzQzZTcwMTVjYjJiM2UzMzg5NmE2OTRjYjczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BEzfzj0KO6TVYj3Ei8_ys3wXT699s69Ni1zmK57lFqQ)

Oky do it
