### ISSUE TITLE
Adding Crypto-Converter 

### ISSUE THREAD

**Issue by TBorundia** [vanshchauhan21/CryptoTracker#224]
I want to add Crypto-Converter to the website.

![image](https://github.com/user-attachments/assets/efa48a2c-2520-47d5-9212-82a2551c91dd)

**Comment by vanshchauhan21** [comment]
> I want to add Crypto-Converter to the website.
> 
> ![image](https://private-user-images.githubusercontent.com/168854094/381401794-efa48a2c-2520-47d5-9212-82a2551c91dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNzQ4MTQsIm5iZiI6MTczMDI3NDUxNCwicGF0aCI6Ii8xNjg4NTQwOTQvMzgxNDAxNzk0LWVmYTQ4YTJjLTI1MjAtNDdkNS05MjEyLTgyYTI1NTFjOTFkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQwNzQ4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzM3NzJkMzRmNTI0M2Q1M2I4MGIxOWJkMTk1Mzk4MGNkNjJlZjU5MDNkYTEyODY4NzQyMjA5NjRlYTBjMGZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ohQ0N6Y_TkZ7FkQ80tsVXjbNFgzCo-FVIGp8ak22hhs)

Oky do it
