### ISSUE TITLE
Adding bit coin rainbow chart

### ISSUE THREAD

**Issue by TBorundia** [vanshchauhan21/CryptoTracker#226]
I want to add "bit coin rainbow chart"

![image](https://github.com/user-attachments/assets/889dd6bb-2638-4d09-b59d-546b9cba2aeb)

**Comment by vanshchauhan21** [comment]
> I want to add "bit coin rainbow chart"
> 
> ![image](https://private-user-images.githubusercontent.com/168854094/381402693-889dd6bb-2638-4d09-b59d-546b9cba2aeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNzQ0NzUsIm5iZiI6MTczMDI3NDE3NSwicGF0aCI6Ii8xNjg4NTQwOTQvMzgxNDAyNjkzLTg4OWRkNmJiLTI2MzgtNGQwOS1iNTlkLTU0NmI5Y2JhMmFlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQwNzQyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWNmMjg3MDc0MjdlNWYxNzZlYTY4MGE3ZTY5OTI1ZTYzZjA5OWIwZWJkMDY1ZTAwMmY1ZjNhMmY5MWEyNjY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WvPzSCPAHY4GaqgUOn-WVe-xueAsRYX9kYWbnvRu9ZQ)

Oky do it
