### ISSUE TITLE
BUG : texts not visible in dark mode

### ISSUE THREAD

**Issue by Irtesaam** [vanshchauhan21/CryptoTracker#230]
When switched to dark mode, "Real time" text becomes invisible.

https://github.com/user-attachments/assets/f0f42083-83c6-4cb6-90d2-abc9a28bc89e

**Comment by vanshchauhan21** [comment]
> When switched to dark mode, "Real time" text becomes invisible.
> 
>  Screencast.from.2024-10-30.13-15-57.mp4

Oky do it
