### ISSUE TITLE
🐛: Misalignment of logo shadow on footer

### ISSUE THREAD

**Issue by Priyanshi0112** [vanshchauhan21/CryptoTracker#248]
### Title

Fix Misalignment of Logo Shadow in Footer

### Bug

Misalignment of Logo Shadow in Footer

### Changes

Corrected the alignment of the logo shadow in the footer to ensure consistent appearance and positioning.
Updated CSS styling for the logo shadow to improve visual coherence and aesthetics across all screen sizes.

### Screenshots 📷

![image](https://github.com/user-attachments/assets/00c876c2-f36c-4034-aef0-29b2c9380d71)

### Full Name

Priyanshi Bhargava

### Participant Role

GSSoC-ext :Contributor

**Comment by vanshchauhan21** [comment]
> ### Title
> Fix Misalignment of Logo Shadow in Footer
> 
> ### Bug
> Misalignment of Logo Shadow in Footer
> 
> ### Changes
> Corrected the alignment of the logo shadow in the footer to ensure consistent appearance and positioning. Updated CSS styling for the logo shadow to improve visual coherence and aesthetics across all screen sizes.
> 
> ### Screenshots 📷
> ![image](https://private-user-images.githubusercontent.com/137524681/381543235-00c876c2-f36c-4034-aef0-29b2c9380d71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyOTQ3NDMsIm5iZiI6MTczMDI5NDQ0MywicGF0aCI6Ii8xMzc1MjQ2ODEvMzgxNTQzMjM1LTAwYzg3NmMyLWYzNmMtNDAzNC1hZWYwLTI5YjJjOTM4MGQ3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQxMzIwNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzE4MmJiZTM1NjBlMDVlZjE2ZWQzZTZlZTQ1OTA5NDhiMzljMGQ4Y2EyNGI5OTY4ZGNlMDc5MDFjYThlNjNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0vR-GBNzcCL5WfxZQLNKlM4q-6bmTxQyU8t6ZquejQA)
> 
> ### Full Name
> Priyanshi Bhargava
> 
> ### Participant Role
> GSSoC-ext :Contributor

Oky do it
