### ISSUE TITLE
🐛:  Impermanent Loss Calculator Page Missing

### ISSUE THREAD

**Issue by ritiksingh-01** [vanshchauhan21/CryptoTracker#278]
### Title

 Impermanent Loss Calculator Page Missing

### Bug

The Impermanent Loss Calculator page is currently inaccessible or missing from the website, affecting users who rely on this tool for their financial calculations. This feature is essential for users engaged in cryptocurrency trading and yield farming, as it helps assess potential losses in liquidity pools. Resolving this will improve user experience by restoring access to a valuable resource and maintaining the platform's utility for all users.

### Changes

NA

### Screenshots 📷

NA

### Full Name

Ritik Singh

### Participant Role

Gssoc - Extd : Contributor

**Comment by vanshchauhan21** [comment]
> ### Title
> Impermanent Loss Calculator Page Missing
> 
> ### Bug
> The Impermanent Loss Calculator page is currently inaccessible or missing from the website, affecting users who rely on this tool for their financial calculations. This feature is essential for users engaged in cryptocurrency trading and yield farming, as it helps assess potential losses in liquidity pools. Resolving this will improve user experience by restoring access to a valuable resource and maintaining the platform's utility for all users.
> 
> ### Changes
> NA
> 
> ### Screenshots 📷
> NA
> 
> ### Full Name
> Ritik Singh
> 
> ### Participant Role
> Gssoc - Extd : Contributor

Do it
