### ISSUE TITLE
🧑‍💻: there should be a "back to top" button

### ISSUE THREAD

**Issue by shar2710** [vanshchauhan21/CryptoTracker#293]
### Title

"Back to Top" button 

### Enhancement Aim

Enhance User Navigation and Accessibility

### Changes

Add a "Back to Top" button at the bottom of every page

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Sejal Sharma

### Participant Role

GSSOC Extd, Hacktoberfest

please assign me with this @vanshchauhan21

**Comment by vanshchauhan21** [comment]
> ### Title
> "Back to Top" button
> 
> ### Enhancement Aim
> Enhance User Navigation and Accessibility
> 
> ### Changes
> Add a "Back to Top" button at the bottom of every page
> 
> ### Screenshots 📷
> _No response_
> 
> ### Guidelines
> * [x]  I have read the guidelines
> * [x]  I have the link to my latest merged PR
> 
> ### Full Name
> Sejal Sharma
> 
> ### Participant Role
> GSSOC Extd, Hacktoberfest
> 
> please assign me with this @vanshchauhan21

Oky I will assign you do it 👍
