### ISSUE TITLE
🐛: Footer is not responsive

### ISSUE THREAD

**Issue by mohdahsanrazakhan** [vanshchauhan21/CryptoTracker#295]
### Title

Footer Responsiveness Issues

### Bug

When the viewport width decreases, the footer may be cut off.

### Changes

I'll fix this bug by adding a few lines of CSS code to the `footer-container` to make the footer responsive.

### Screenshots 📷

![image](https://github.com/user-attachments/assets/aba1f208-60aa-420b-8dca-d701cdd47924)

### Full Name

Mohd Ahsan Raza Khan

### Participant Role

GSSOC, GSOC, Hacktoberfest

**Comment by vanshchauhan21** [comment]
> ### Title
> Footer Responsiveness Issues
> 
> ### Bug
> When the viewport width decreases, the footer may be cut off.
> 
> ### Changes
> I'll fix this bug by adding a few lines of CSS code to the `footer-container` to make the footer responsive.
> 
> ### Screenshots 📷
> ![image](https://private-user-images.githubusercontent.com/57056757/381949872-aba1f208-60aa-420b-8dca-d701cdd47924.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzODQzNzAsIm5iZiI6MTczMDM4NDA3MCwicGF0aCI6Ii81NzA1Njc1Ny8zODE5NDk4NzItYWJhMWYyMDgtNjBhYS00MjBiLThkY2EtZDcwMWNkZDQ3OTI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDE0MTQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNTBiNTMzZDExMjYwMmZiZGI1YTlmMGY3ODdkYjQxNzc5ZjAxMzQzZGE2Y2IxNDU5Mzc0MTUxNDFhNWFhNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yQJCA3NRJybfLf-sqTye3UUsXjvQ58whJVhFkfYK7oE)
> 
> ### Full Name
> Mohd Ahsan Raza Khan
> 
> ### Participant Role
> GSSOC, GSOC, Hacktoberfest

I will assign you do it your best
