### ISSUE TITLE
Adding 24h cryptocurrency market

### ISSUE THREAD

**Issue by TBorundia** [vanshchauhan21/CryptoTracker#299]
![Screenshot 2024-10-30 105040](https://github.com/user-attachments/assets/65050f3c-842b-4899-b8ba-42906b8e9081)

**Comment by vanshchauhan21** [comment]
> ![Screenshot 2024-10-30 105040](https://private-user-images.githubusercontent.com/168854094/382021939-65050f3c-842b-4899-b8ba-42906b8e9081.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzOTY4NDYsIm5iZiI6MTczMDM5NjU0NiwicGF0aCI6Ii8xNjg4NTQwOTQvMzgyMDIxOTM5LTY1MDUwZjNjLTg0MmItNDg5OS1iOGJhLTQyOTA2YjhlOTA4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxNzQyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMTJiYjkzODUxNmY0YmMzNTIxNzQyMDE0MmM0YWMyZThjMjE5MjAwNzg2MDIyZTljMTY1YWZmNWJjMzhlM2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4mUD5wh9ACbLgmIiAHtS6ajrWOfITNDfK1dFt0AxWUY)

👍
