### ISSUE TITLE
🧑‍💻: Add Contributors section

### ISSUE THREAD

**Issue by yashksaini-coder** [vanshchauhan21/CryptoTracker#312]
### Title

Contributors section

### Enhancement Aim

I proposed to add a page for the contributors to display their profile and the number of contributions they done so far in the project.

### Changes

- Create a new page for contributors accessed from the Navbar or from the footer listed items
- Simple Javascript script to fetch the data and then display it on the contributors
- Ensuring Pagination to load few chunk of data, and call another chunk once user loads to the end of the page 

### Screenshots 📷

![image](https://github.com/user-attachments/assets/a24df87a-36f4-458e-9cca-9e939f5b3ad8)

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

[Yash K. Saini](https://github.com/yashksaini-coder)

### Participant Role

GSSoC-Ext

**Comment by yashksaini-coder** [comment]
@vanshchauhan21 can you assign this issue to me with proper labels

**Comment by vanshchauhan21** [comment]
> @vanshchauhan21 can you assign this issue to me with proper labels

Bro this issue is already assigned and already merged

**Comment by yashksaini-coder** [comment]
![image](https://github.com/user-attachments/assets/e7fbd5e1-7564-4106-80d1-902353ac3337)

Sorry My bad, didn't see the button there properly

**Comment by vanshchauhan21** [comment]
> ![image](https://private-user-images.githubusercontent.com/115717039/382193395-e7fbd5e1-7564-4106-80d1-902353ac3337.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NDIwMjIsIm5iZiI6MTczMDQ0MTcyMiwicGF0aCI6Ii8xMTU3MTcwMzkvMzgyMTkzMzk1LWU3ZmJkNWUxLTc1NjQtNDEwNi04MGQxLTkwMjM1M2FjMzMzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQwNjE1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTU3YWYwMjM0YjYzN2FiY2Q4Yjc1ZjgyYjliN2U0ZWNjNjVjMWFiNGRiZmQ3OTg4Y2ZiM2ZjMWIxYTQ2MjIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8CzXKWcVSJ6kw42QFuyXGuBAL9BuuU04cCODnNB3XQY)
> 
> Sorry My bad, didn't see the button there properly

Np
