### ISSUE TITLE
FEAT :  Improve compare page

### ISSUE THREAD

**Issue by Irtesaam** [vanshchauhan21/CryptoTracker#316]
### Title

UI/UX Enhancements for Compare Page

### Enhancement Aim

Improves Dialog Boxes, Graph Visibility, About Text Styling and overall UI.

### Changes

The compare page as of now can be improved using the enhancements in the following areas : 
1) Improving crypto1 & crypto2 dialog box in dark mode and its alignment
2) Improving the graph size and visibility across themes
3) Improving the crypto's about text below the graph using better fonts and styles.

### Screenshots 📷

![image](https://github.com/user-attachments/assets/3d59ed40-9667-4426-8747-59e87b331eeb)

![image](https://github.com/user-attachments/assets/74961e1a-49d2-43a1-a6af-c536d5d6f2d5)

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Irtesaam Atfi

### Participant Role

GSSoC
WoB
Hacktoberfest

**Comment by RachitSahu26** [comment]
Hey @Irtesaam  tell me about WoB this is also GSSoc type

**Comment by vanshchauhan21** [comment]
> Hey @Irtesaam tell me about WoB this is also GSSoc type

It's merged with gssoc

**Comment by Irtesaam** [comment]
> Hey @Irtesaam tell me about WoB this is also GSSoc type

Yes. Both are organized by GirlScript foundation and have kind of similar projects. However, WoB focuses more on blockchain related projects.
You can have a look at WoB projects over here [Projects](https://wob.girlscript.tech/wobProject)
