### ISSUE TITLE
subscription via email

### ISSUE THREAD

**Issue by Tanisha0708** [vanshchauhan21/CryptoTracker#344]
there is email login block for subscription . It will be not detecting the fake emails . this will cause malware attacks . 
here find some technique to detect the fake email and give a warning

![Screenshot 2024-11-01 233350](https://github.com/user-attachments/assets/93859622-599c-4924-a7a3-64d6b0e3e6aa)

<h1> Issue regarding fake emails </h1>

**Comment by divyaaa16** [comment]
@Tanisha0708 I would like to work on this issue, Please assign me this issue.

**Comment by Tanisha0708** [comment]
@vanshchauhan21  will assign you this issue

**Comment by vanshchauhan21** [comment]
> @vanshchauhan21 will assign you this issue

I already assigned you tanisha

**Comment by Tanisha0708** [comment]
@vanshchauhan21  yes

> > @vanshchauhan21 will assign you this issue
> 
> I already assigned you tanisha
