### ISSUE TITLE
🐛: Content Visibility Issue in Dark Mode on Impermanent Loss Calculator page 

### ISSUE THREAD

**Issue by Priyanshi0112** [vanshchauhan21/CryptoTracker#349]
### Title

Content Visibility Issue in Dark Mode on Impermanent Loss Calculator page 

### Bug

Some content on the Crypto Converter page is not visible in dark mode, causing usability issues for users viewing the page with the dark theme enabled.

### Changes

none

### Screenshots 📷

![image](https://github.com/user-attachments/assets/5e129aff-1b25-4263-b02e-371077b852a8)

### Full Name

Priyanshi Bhargava

### Participant Role

GSSoC-ext :  Contributor

**Comment by Tanisha0708** [comment]
@Priyanshi0112  please assign me this issue i would like to work

**Comment by vanshchauhan21** [comment]
> @Priyanshi0112 please assign me this issue i would like to work

@Priyanshi0112 
@Tanisha0708 
I assigned both of you
Let's see who will do first
