### ISSUE TITLE
Adding Social Media Links to the Footer of README

### ISSUE THREAD

**Issue by amiya-cyber** [vanshchauhan21/CryptoTracker#371]
Add a visually appealing footer to the README that includes links to key social media profiles, making it easy for users to connect and stay updated. The footer should align with the project's branding, feature accessible icons (e.g., GitHub, Twitter, LinkedIn), and be mobile-friendly. Each link must be verified to open correctly, ideally in a new tab where possible. This enhancement will improve user engagement and provide quick access to our social platforms.

![2024-11-01 (6)](https://github.com/user-attachments/assets/2fec75ae-9640-4d99-b1de-94f0531668cf)

**Comment by Tanisha0708** [comment]
@vanshchauhan21  i would like to work on this issue please assign me this
