### ISSUE TITLE
Adding icons of social media handles

### ISSUE THREAD

**Issue by tanishirai** [vanshchauhan21/CryptoTracker#39]
Adding social media icons to a site boosts user engagement and facilitates easy access to your social profiles.

![image](https://github.com/user-attachments/assets/0f26f505-3021-4c96-88c4-54428526c90a)

**Comment by tanishirai** [comment]
@vanshchauhan21 
Please add label for gssoc-extd also

**Comment by vanshchauhan21** [comment]
> @vanshchauhan21 Please add label for gssoc-extd also

Oky but you have to remove social media names , only icons
