### ISSUE TITLE
Making logo responsive

### ISSUE THREAD

**Issue by Saipradyumnagoud** [vanshchauhan21/CryptoTracker#4]
When we press logo we are not getting redirect in to the home page

**Comment by Saipradyumnagoud** [comment]
@vanshchauhan21 Please assign me the issue

**Comment by mahenoorsalat** [comment]
I have a strong foundation on front-End Technologies . so I am willing to contribute to this project ..please assign me this issues . I am looking forward to your prompt reply 

Thank you :)

**Comment by vanshchauhan21** [comment]
> @vanshchauhan21 Please assign me the issue

Okay

**Comment by vanshchauhan21** [comment]
> I have a strong foundation on front-End Technologies . so I am willing to contribute to this project ..please assign me this issues . I am looking forward to your prompt reply
> 
> Thank you :)

Okay
