### ISSUE TITLE
🧑‍💻: Add a page of Trending news in footer (news section) & fetch it from NEWS API

### ISSUE THREAD

**Issue by mehul-m-prajapati** [vanshchauhan21/CryptoTracker#426]
### Title

Add a page of Add a page of Trending news in footer (news section) & fetch it from NEWS APInews in footer (news section) & fetch it from NEWS API

### Enhancement Aim

Get Trending news

### Changes

Add new page and route

### Screenshots 📷

![p1](https://github.com/user-attachments/assets/217a2cf5-6d83-48f5-a74d-1a7c0010c66c)
### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Mehul P

### Participant Role

GSSOC-Ext

**Comment by RachitSahu26** [comment]
Bro it has already created  @vanshchauhan21 @mehul-m-prajapati

**Comment by mehul-m-prajapati** [comment]
okay @RachitSahu26 , you can work on it

**Comment by RachitSahu26** [comment]
> okay @RachitSahu26 , you can work on it
ya because i have created this issue yesterday night @mehul-m-prajapati
