### ISSUE TITLE
🧑‍💻:Add Blog Separate Route (Page) 

### ISSUE THREAD

**Issue by RachitSahu26** [vanshchauhan21/CryptoTracker#427]
### Title

BTC-Dominance Dark mode Improvement 

### Enhancement Aim

NA

### Changes

Na

### Screenshots 📷

![Screenshot (452)](https://github.com/user-attachments/assets/ff6d9cd9-5a96-4572-8e28-07c4609937ef)

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Rachit Sahu

### Participant Role

GSSoC

**Comment by Priyanshi0112** [comment]
@vanshchauhan21  It is already corrected 
![image](https://github.com/user-attachments/assets/e6b06929-857d-4e53-beeb-10f2987d9e8b)

**Comment by RachitSahu26** [comment]
> @vanshchauhan21 It is already corrected ![image](https://private-user-images.githubusercontent.com/137524681/382789379-e6b06929-857d-4e53-beeb-10f2987d9e8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MzA1MjYsIm5iZiI6MTczMDczMDIyNiwicGF0aCI6Ii8xMzc1MjQ2ODEvMzgyNzg5Mzc5LWU2YjA2OTI5LTg1N2QtNGU1My1iZWViLTEwZjI5ODdkOWU4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxNDIzNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjdlYjliZTVmNjRkZWU5NjFjYjljNDc2NDRkMzllNzgzYjY5NGRiN2U4ZGVjODAzNTU5YTY0MGNiYmYzNzhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.u6HbY82sgJ77b7zwyx1t8AJfm3tan3znpGMijYrAG8A)

okay i noticed now

**Comment by RachitSahu26** [comment]
but tell me why did you change footer link @Priyanshi0112

**Comment by vanshchauhan21** [comment]
> but tell me why did you change footer link @Priyanshi0112



> but tell me why did you change footer link @Priyanshi0112

Don't argue with eachother please

**Comment by vanshchauhan21** [comment]
> but tell me why did you change footer link @Priyanshi0112

Which footer link ?
