### ISSUE TITLE
Missing text when Light theme used

### ISSUE THREAD

**Issue by RushilJalal** [vanshchauhan21/CryptoTracker#43]
On the home page, the text "Track Crypto" is white, irrespective of the theme being used.
Thus, when light theme is used, the text is not visible until the mouse is hovered on it, which is bad design.
I would like to work on this issue.

![image](https://github.com/user-attachments/assets/1b317964-9827-423a-8fe0-d0760675eb6a)

**Comment by vanshchauhan21** [comment]
> On the home page, the text "Track Crypto" is white, irrespective of the theme being used. Thus, when light theme is used, the text is not visible until the mouse is hovered on it, which is bad design. I would like to work on this issue.
> 
> ![image](https://private-user-images.githubusercontent.com/54212357/378728915-1b317964-9827-423a-8fe0-d0760675eb6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1OTE5NzUsIm5iZiI6MTcyOTU5MTY3NSwicGF0aCI6Ii81NDIxMjM1Ny8zNzg3Mjg5MTUtMWIzMTc5NjQtOTgyNy00MjNhLThmZTAtZDA3NjA2NzVlYjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDEwMDc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZTkxNWExYjVkNmIwNDZjNDc5YTc4Njg4ZmMyM2RlMWQ2ZDU3NDViMDY0YTEyMzQxZDU4MDk2YTNhYmViZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t-l2byg_Fx3VdG3QQBx8aFI3Ax0VNmzVrKspkP8Cej4)

Yes you can do , all the best
