### ISSUE TITLE
Dashboard is not loading

### ISSUE THREAD

**Issue by RushilJalal** [vanshchauhan21/CryptoTracker#44]
Clicking the dashboard button doesn't load the page.

![image](https://github.com/user-attachments/assets/8425d916-0c4a-44bf-a92c-8c9fbfc5ea1b)

**Comment by vanshchauhan21** [comment]
> Clicking the dashboard button doesn't load the page.
> 
> ![image](https://private-user-images.githubusercontent.com/54212357/378729795-8425d916-0c4a-44bf-a92c-8c9fbfc5ea1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1OTIxMTAsIm5iZiI6MTcyOTU5MTgxMCwicGF0aCI6Ii81NDIxMjM1Ny8zNzg3Mjk3OTUtODQyNWQ5MTYtMGM0YS00NGJmLWE5MmMtOGM5ZmJmYzVlYTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDEwMTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMGM2NTRhOTE2NzYzMWNjZTIyZGVlMzc2NjNhNjFjMWI1YWI1NjY2MWFlMmJlNTM1Y2U2MjRmZmY5YTQ1MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iA6BjxlnWeFIinNKUlqimkLhOKjOtLCSYXMJdD90yME)

So what should do?

**Comment by RushilJalal** [comment]
@vanshchauhan21  do you mean "what should we do"?

**Comment by RushilJalal** [comment]
@vanshchauhan21 it works now by itself, didn't make any changes.
