### ISSUE TITLE
Add Terms and Conditions Link to Footer

### ISSUE THREAD

**Issue by RachitSahu26** [vanshchauhan21/CryptoTracker#45]
The footer currently lacks a link to the Terms and Conditions page, which is essential for providing users with legal information about the use of the platform. Adding this link will improve transparency and user trust.
I would like to work on it @vanshchauhan21 
Could you please assign it to me

**Comment by vanshchauhan21** [comment]
> The footer currently lacks a link to the Terms and Conditions page, which is essential for providing users with legal information about the use of the platform. Adding this link will improve transparency and user trust. I would like to work on it @vanshchauhan21 Could you please assign it to me

Oky Brother all the best

**Comment by RachitSahu26** [comment]
okay i am going to work on it
