### ISSUE TITLE
🐛: Crypto News Content Not Displaying in News Container

### ISSUE THREAD

**Issue by Priyanshi0112** [vanshchauhan21/CryptoTracker#456]
### Title

Crypto News Content Not Displaying in News Container

### Bug

There is an issue where, upon clicking on "Crypto News," only the news container appears without any news content inside it. The news articles are not loading or displaying as expected, resulting in an empty container. This issue needs to be investigated to ensure that relevant crypto news is fetched and rendered properly in the news section, providing users with the latest updates and information.

### Changes

none

### Full Name

Priyanshi Bhargava

### Participant Role

GSSoC- ext : Contributor

**Comment by mehul-m-prajapati** [comment]
@Priyanshi0112 : Look at this PR #423 description.

You need to register on News API site and get key. Set that key on .env

**Comment by Priyanshi0112** [comment]
@mehul-m-prajapati okay
