### ISSUE TITLE
Feat: Create a Dedicated Privacy Policy Page

### ISSUE THREAD

**Issue by RachitSahu26** [vanshchauhan21/CryptoTracker#46]
The Privacy Policy link in the footer redirects nowhere or shows no content, as there is no dedicated page for it. To maintain transparency and meet user expectations, we need to create a separate, informative Privacy Policy page. This page will outline the platform's data practices, ensuring compliance with privacy standards and building user trust.

I would like to work on it @vanshchauhan21 
Could you please assign it to me

**Comment by vanshchauhan21** [comment]
> The Privacy Policy link in the footer redirects nowhere or shows no content, as there is no dedicated page for it. To maintain transparency and meet user expectations, we need to create a separate, informative Privacy Policy page. This page will outline the platform's data practices, ensuring compliance with privacy standards and building user trust.
> 
> I would like to work on it @vanshchauhan21 Could you please assign it to me

Oky brother I will assign you, all the best
