### ISSUE TITLE
 🐞Blog Page does  not exist and Info of it

### ISSUE THREAD

**Issue by RachitSahu26** [vanshchauhan21/CryptoTracker#468]
Blog Page

**Comment by mehul-m-prajapati** [comment]
@RachitSahu26 : Refresh the page after 1 min, it might be 429 too many requests for coingecko

**Comment by mehul-m-prajapati** [comment]
![c1](https://github.com/user-attachments/assets/c56ca452-9390-491a-9c4e-2a9d33155b18)
