### ISSUE TITLE
ADD a di to home page for Daily/Weekly Percentage Change:

### ISSUE THREAD

**Issue by shubhagarwal1** [vanshchauhan21/CryptoTracker#472]
Daily/Weekly Percentage Change:

Add a section showing the daily and weekly percentage changes for each cryptocurrency.
You could use color coding (e.g., green for positive, red for negative) to make changes stand out visually.

**Comment by RachitSahu26** [comment]
> Daily/Weekly Percentage Change:
> 
> Add a section showing the daily and weekly percentage changes for each cryptocurrency. You could use color coding (e.g., green for positive, red for negative) to make changes stand out visually.

sorry write now whatever that issue i am creating by some reason maintainer can not add label so i am raising my pr this is issue
@vanshchauhan21
