### ISSUE TITLE
🐞: Crypto News Route Fails to Display Data - Possible API Fetching Issue

### ISSUE THREAD

**Issue by RachitSahu26** [vanshchauhan21/CryptoTracker#488]
This title addresses the issue of no data being shown on the crypto news route and indicates that the problem may be related to fetching data from the API.

![Screenshot (467)](https://github.com/user-attachments/assets/eac443c5-a8bd-4c95-a027-b80e13053812)

**Comment by mehul-m-prajapati** [comment]
@RachitSahu26 : @vanshchauhan21 : Look at this PR https://github.com/vanshchauhan21/CryptoTracker/pull/423 description.

You need to register on News API site and get key. Set that key in .env file

You can update README regarding this

**Comment by mehul-m-prajapati** [comment]
@RachitSahu26 : Please look at other changes and .env file. Dont blindly push issues
