### ISSUE TITLE
🧑‍💻: Add Earn page in footer to show profitable coins for users

### ISSUE THREAD

**Issue by mehul-m-prajapati** [vanshchauhan21/CryptoTracker#494]
### Title

🧑‍💻: Add Earn page in footer to show profitable coins for users

### Enhancement Aim

To get profit coin

### Changes

add new page

### Screenshots 📷

![q1](https://github.com/user-attachments/assets/9201fb74-2971-44a9-93fc-a375643ae40c)

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Mehul P

### Participant Role

GSSOC-Ext

**Comment by RachitSahu26** [comment]
@mehul-m-prajapati first you should check that an issue has already created or not then create any issue its has already created mehul bro

**Comment by RachitSahu26** [comment]
@mehul-m-prajapati  could you again mention it i don't know which pr your are taking about

**Comment by mehul-m-prajapati** [comment]
@RachitSahu26 : https://github.com/vanshchauhan21/CryptoTracker/pull/430
