### ISSUE TITLE
BUG: Cannot give graphs on comparing in different time duration in few coins

### ISSUE THREAD

**Issue by Jagpreet153** [vanshchauhan21/CryptoTracker#5]
![Screenshot 2024-09-29 015639](https://github.com/user-attachments/assets/61367d64-1988-4144-8b16-8fb55a85cccf)
![Screenshot 2024-09-29 015843](https://github.com/user-attachments/assets/896e6dae-1ba1-44c7-91e0-a7825943356e)

Please assign this issue to me I would like to resolve it

**Comment by vanshchauhan21** [comment]
Oky

**Comment by Jagpreet153** [comment]
@vanshchauhan21 Assign it under WOB'24

**Comment by Jagpreet153** [comment]
![Screenshot 2024-09-29 122525](https://github.com/user-attachments/assets/af19e670-a188-42a9-8973-ac655b38a2ee)
 
Sorry it was due to api pricing issue
