### ISSUE TITLE
The iphone image gradient is overflowing into other content

### ISSUE THREAD

**Issue by RushilJalal** [vanshchauhan21/CryptoTracker#50]
![image](https://github.com/user-attachments/assets/80d8e67a-c268-4f3e-939c-3e0adb0d12c6)

I can fix it, although i cannot be sure if it looks good on other devices, even though it looks good on mine.

**Comment by vanshchauhan21** [comment]
Okay I will assign you

**Comment by vanshchauhan21** [comment]
> ![image](https://private-user-images.githubusercontent.com/54212357/378888562-80d8e67a-c268-4f3e-939c-3e0adb0d12c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NjM0MDAsIm5iZiI6MTcyOTc2MzEwMCwicGF0aCI6Ii81NDIxMjM1Ny8zNzg4ODg1NjItODBkOGU2N2EtYzI2OC00ZjNlLTkzOWMtM2UwYWRiMGQxMmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDA5NDUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmMjA0Mjk4NzQ2NzgwNzNhOTczZTAyNGQ1YTYxMjNlNmFjZDgwNzI4MzllNzhmNDcwYzc2ZmViOTk3ODEwNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6s1ZmHYgTDQgYKHsH3acbjtoHkAwgA8BiXa9ihTFqcc)
> 
> I can fix it, although i cannot be sure if it looks good on other devices, even though it looks good on mine.

Bro image overlapping in android mode , resolve it make it responsive

**Comment by RushilJalal** [comment]
@vanshchauhan21 i checked. it isnt overlapping on my phone
