### ISSUE TITLE
🐛: content visibility issue on Crypto Tracker and rewards page 

### ISSUE THREAD

**Issue by Priyanshi0112** [vanshchauhan21/CryptoTracker#504]
### Title

content visibility issue on Crypto Tracker and rewards page 

### Bug

N/A

### Changes

N/A

### Screenshots 📷

https://github.com/user-attachments/assets/8f757101-93a5-45b4-aedf-632a8009b98b

### Full Name

Priyanshi Bhargava

### Participant Role

GSSoC- ext

**Comment by RachitSahu26** [comment]
Already resolve @Priyanshi0112 dublicate issue @vanshchauhan21
