### ISSUE TITLE
🧑‍💻: Add "Users Sharing Their Experience" Section on About Us Page

### ISSUE THREAD

**Issue by Priyanshi0112** [vanshchauhan21/CryptoTracker#516]
### Title

Add "Users Sharing Their Experience" Section on About Us Page

### Enhancement Aim

none

### Changes

none

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Priyanshi Bhargava

### Participant Role

GSSoC-ext

**Comment by Priyanshi0112** [comment]
@vanshchauhan21 it is about the feedback they have shared 

![image](https://github.com/user-attachments/assets/4eadbf72-f02c-477c-a67b-f52db99cac5b)

**Comment by vanshchauhan21** [comment]
> @vanshchauhan21 it is about the feedback they have shared
> 
> ![image](https://private-user-images.githubusercontent.com/137524681/383669891-4eadbf72-f02c-477c-a67b-f52db99cac5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjM3MzgsIm5iZiI6MTczMDk2MzQzOCwicGF0aCI6Ii8xMzc1MjQ2ODEvMzgzNjY5ODkxLTRlYWRiZjcyLWYwMmMtNDc3Yy1hNjdiLWY1MmRiOTljYWM1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QwNzEwMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGE2ZTJiZGVlNThmMDQzMjZlZDczYjQ5OTQ4M2JiZmY1ZTc5MGE5OWQ0MzRiYjU3MzBjNjQwYjdjMGE2YjVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-Fdb-8S-Akfb8HD-Cph710KWRHKNrb9znrQ1DY9i0z4)

Okay do it
