### ISSUE TITLE
🧑‍💻: Adding a blog page 

### ISSUE THREAD

**Issue by Priyanshi0112** [vanshchauhan21/CryptoTracker#531]
### Title

Adding a blog page 

### Enhancement Aim

N/A

### Changes

N/A

### Guidelines

- [X] I have read the guidelines
- [X] I have the link to my latest merged PR

### Full Name

Priyanshi Bhargava

### Participant Role

GSSoC- ext

**Comment by RachitSahu26** [comment]
dublicate issue #540 @Priyanshi0112  @vanshchauhan21

**Comment by Priyanshi0112** [comment]
@RachitSahu26 
Let your  issue get merged, I'll make the changes  in my issue

**Comment by vanshchauhan21** [comment]
> @RachitSahu26 Let your issue get merged, I'll make the changes in my issue

Do it I assigned you
