### ISSUE TITLE
Create a login/signup page.

### ISSUE THREAD

**Issue by sayanp607** [vanshchauhan21/CryptoTracker#62]
Adding an authorization page will be better for user to keep themselves registered here. Website quality will reach it's max . Please assign this task to me. I will create both the pages.
![Screenshot 2024-10-19 111343](https://github.com/user-attachments/assets/e181bede-3df0-42d4-b243-fd75013ffced)
Like this.

**Comment by vanshchauhan21** [comment]
> Adding an authorization page will be better for user to keep themselves registered here. Website quality will reach it's max . Please assign this task to me. I will create both the pages. ![Screenshot 2024-10-19 111343](https://private-user-images.githubusercontent.com/170846702/379163622-e181bede-3df0-42d4-b243-fd75013ffced.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2ODE2OTMsIm5iZiI6MTcyOTY4MTM5MywicGF0aCI6Ii8xNzA4NDY3MDIvMzc5MTYzNjIyLWUxODFiZWRlLTNkZjAtNDJkNC1iMjQzLWZkNzUwMTNmZmNlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QxMTAzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDc0YTgxMzRiY2NmMjQ3YmQ0NDQ0MTIxMzU1NTA2NGJmMjE1MDI3NzhmMWQ0MzMxOTgwYzhmMWQ4MmM0YWUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AgX66eUZ2PdJ34aPTDo0GlFGwvVRhjqocXLI11HBJuU) Like this.

Oky I will assign you all the best
