### ISSUE TITLE
add a FAQ section in footer.

### ISSUE THREAD

**Issue by sayanp607** [vanshchauhan21/CryptoTracker#63]
I would like to add a FAQ section link in footer. After clicking the link, user will redirect to the page , it will contain questions and answers . Answers will be opened after click on the respective questions. Please assign this task to me, I will create it surely.

**Comment by vanshchauhan21** [comment]
> I would like to add a FAQ section link in footer. After clicking the link, user will redirect to the page , it will contain questions and answers . Answers will be opened after click on the respective questions. Please assign this task to me, I will create it surely.

Oky brother
