### ISSUE TITLE
Watchlist text disappear in light mode.

### ISSUE THREAD

**Issue by sayanp607** [vanshchauhan21/CryptoTracker#64]
https://github.com/user-attachments/assets/bbbddd56-a33f-4b34-a78a-b6ff940d92d0

I want to fix this issue . Please assign this to me.

**Comment by vanshchauhan21** [comment]
> Screen.Recording.2024-10-23.134800.mp4 
> I want to fix this issue . Please assign this to me.

Oky do it.
