### ISSUE TITLE
 Add Multi-language Support for Page Translation

### ISSUE THREAD

**Issue by RachitSahu26** [vanshchauhan21/CryptoTracker#76]
To make the platform more accessible to a global audience, we should implement multi-language support. This feature will allow users to switch the website's content to their preferred language seamlessly. Integrating popular languages like Spanish, French, and German would enhance user experience and expand the reach of the platform.

Expected Behavior:

Provide a language switcher on the UI for easy access.
Translate static text into selected languages.
Ensure that translated content loads efficiently without disrupting the page flow.
![Screenshot (389)](https://github.com/user-attachments/assets/5a73f449-0ae5-4975-a15b-e498b625792c)

**Comment by RachitSahu26** [comment]
If you assign me, I would love to work on this. Please assign this to me @vanshchauhan21

**Comment by vanshchauhan21** [comment]
> If you assign me, I would love to work on this. Please assign this to me @vanshchauhan21

Okay do it 😀

**Comment by RachitSahu26** [comment]
please check it my PR @vanshchauhan21

**Comment by RachitSahu26** [comment]
Vansh bhai add here level 3 @vanshchauhan21

**Comment by vanshchauhan21** [comment]
> Vansh bhai add here level 3 @vanshchauhan21

Done bro
