### ISSUE TITLE
Incomplete Privacy Policy Page

### ISSUE THREAD

**Issue by PriyaD17** [vanshchauhan21/CryptoTracker#77]
The privacy policy page is currently incomplete, lacking essential sections that inform users about data handling, user rights, and security measures. This could lead to confusion and mistrust among users regarding how their data is managed.

**Comment by RachitSahu26** [comment]
i asked to before in my previous PR that can i work on this because i have created a sprate  page (route) for the Privacy policy @vanshchauhan21

**Comment by vanshchauhan21** [comment]
> i asked to you before in my previous PR that can i work on this because i have created a separate page (route) for the Privacy policy @vanshchauhan21

Yes you can work on this

**Comment by PriyaD17** [comment]
@vanshchauhan21 I already raised the pr when it was assigned to me

**Comment by RachitSahu26** [comment]
Message for Maintainer
Hi [Maintainer's Name],

I wanted to bring to your attention that another contributor has submitted a pull request related to the same issue I was assigned regarding the Privacy Policy page. However, this contributor has used styled components, which is against our project's guidelines. As you know, we have established a standard to use regular CSS instead of styled components for consistency and maintainability.

I have already completed my work on the Privacy Policy page, adhering to the project's standards by using proper CSS. I believe my implementation aligns with the project's best practices, and I would appreciate your consideration in merging my pull request instead.

Thank you for your attention to this matter! @vanshchauhan21

**Comment by RachitSahu26** [comment]
![Screenshot (400)](https://github.com/user-attachments/assets/390d483f-8b78-429e-b6af-1e860f69d830)
Please add labels

**Comment by vanshchauhan21** [comment]
> ![Screenshot (400)](https://private-user-images.githubusercontent.com/129506267/380034392-390d483f-8b78-429e-b6af-1e860f69d830.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTU5NTEsIm5iZiI6MTcyOTg1NTY1MSwicGF0aCI6Ii8xMjk1MDYyNjcvMzgwMDM0MzkyLTM5MGQ0ODNmLThiNzgtNDI5ZS1iNmFmLTFlODYwZjY5ZDgzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxMTI3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTU1NTg4Y2FiYTIwZmZjOGIwODhlMjRhYmJjNDkyMThmN2Y5OGYzZDJiODYyZjhkMThjZjQ4NTQxYjE2ZGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.77NQZTpM3H-e3NzYMlfLVuxZl6sXAuhwit3CI7N05Uw) Please add labels

Already added bro

**Comment by vanshchauhan21** [comment]
> Message for Maintainer Hi [Maintainer's Name],
> 
> I wanted to bring to your attention that another contributor has submitted a pull request related to the same issue I was assigned regarding the Privacy Policy page. However, this contributor has used styled components, which is against our project's guidelines. As you know, we have established a standard to use regular CSS instead of styled components for consistency and maintainability.
> 
> I have already completed my work on the Privacy Policy page, adhering to the project's standards by using proper CSS. I believe my implementation aligns with the project's best practices, and I would appreciate your consideration in merging my pull request instead.
> 
> Thank you for your attention to this matter! @vanshchauhan21

Okay okay

**Comment by vanshchauhan21** [comment]
> > Message for Maintainer Hi [Maintainer's Name],
> > I wanted to bring to your attention that another contributor has submitted a pull request related to the same issue I was assigned regarding the Privacy Policy page. However, this contributor has used styled components, which is against our project's guidelines. As you know, we have established a standard to use regular CSS instead of styled components for consistency and maintainability.
> > I have already completed my work on the Privacy Policy page, adhering to the project's standards by using proper CSS. I believe my implementation aligns with the project's best practices, and I would appreciate your consideration in merging my pull request instead.
> > Thank you for your attention to this matter! @vanshchauhan21
> 
> Okay okay

Actually there are so many contributers so i am little confused sometimes sorry for this issue, this will not happen again

**Comment by PriyaD17** [comment]
@RachitSahu26 @vanshchauhan21 
Let me know where such guidelines were given cause I read the contribution.md before making the pr, but I couldn't see it written anywhere explicitly 
Also I am new to open source and found it interesting that it's been upgraded to level 2 since this issue requires minimal coding effort, are other level 2 issues are too of this difficulty level ?

**Comment by vanshchauhan21** [comment]
> @RachitSahu26 @vanshchauhan21 Let me know where such guidelines were given cause I read the contribution.md before making the pr, but I couldn't see it written anywhere explicitly Also I am new to open source and found it interesting that it's been upgraded to level 2 since this issue requires minimal coding effort, are other level 2 issues are too of this difficulty level ?

you can create new issue
