### ISSUE TITLE
Adding a multi language support

### ISSUE THREAD

**Issue by sayanp607** [vanshchauhan21/CryptoTracker#82]
![Screenshot 2024-10-24 104209](https://github.com/user-attachments/assets/f4563671-52b8-4e87-8c51-2eba045bf7a9)
Like this. By this user of different language can use this website very fluently and without any hesitation. Then, there will be no tension of understanding English for anyone to use the website. Please assign this task to me.

**Comment by vanshchauhan21** [comment]
> ![Screenshot 2024-10-24 104209](https://private-user-images.githubusercontent.com/170846702/379622983-f4563671-52b8-4e87-8c51-2eba045bf7a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NjI0NzYsIm5iZiI6MTcyOTc2MjE3NiwicGF0aCI6Ii8xNzA4NDY3MDIvMzc5NjIyOTgzLWY0NTYzNjcxLTUyYjgtNGU4Ny04YzUxLTJlYmEwNDViZjdhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQwOTI5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGU2NWNjMjBhMjdlYmMxMjViMTVjZmQxZWE2NDY1OTkwNTg2YTUwZDAzZWM3ZTZjNGY4MWZkZGFjMTIwODcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4F02sjuSlNgw56VNFTpMPKU27Hjhw6v82OGxwKyYyQI) Like this. By this user of different language can use this website very fluently and without any hesitation. Then, there will be no tension of understanding English for anyone to use the website. Please assign this task to me.

Oky I will assign you for this issue
