### ISSUE TITLE
Add a Chatbot option 

### ISSUE THREAD

**Issue by sayanp607** [vanshchauhan21/CryptoTracker#83]
![Screenshot 2024-10-24 104803](https://github.com/user-attachments/assets/c38c59a7-97ca-4aa7-8716-f1272ab598b3)
This will be helpful for user to ask anything  related to crypto currency if they want  to this chatbot. It will answer everything. Please assign this task to me with proper badge and level.

**Comment by vanshchauhan21** [comment]
> ![Screenshot 2024-10-24 104803](https://private-user-images.githubusercontent.com/170846702/379624233-c38c59a7-97ca-4aa7-8716-f1272ab598b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NjI0NDgsIm5iZiI6MTcyOTc2MjE0OCwicGF0aCI6Ii8xNzA4NDY3MDIvMzc5NjI0MjMzLWMzOGM1OWE3LTk3Y2EtNGFhNy04NzE2LWYxMjcyYWI1OThiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQwOTI5MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MWIwODEzZjc1NGQ5ODIyODhiYzdjYzdkZTg3NzA1MzZmZmY4MWY1ZjkwMDcyOTYyMTM4MzQ5YjI5OGI2MGJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZW8G46zNXCfkwaIwEJt1qRnbp119MMK4BkmsulyltsI) This will be helpful for user to ask anything related to crypto currency if they want to this chatbot. It will answer everything. Please assign this task to me with proper badge and level.

Okay do it bro and all the best
