### ISSUE TITLE
[BUG] Text not visible in dark mode 

### ISSUE THREAD

**Issue by sezallagwal** [vanshchauhan21/CryptoTracker#88]
![image](https://github.com/user-attachments/assets/3dfaa54a-e361-44e8-8848-90ae41c4fcf8)
![image](https://github.com/user-attachments/assets/bbf4108f-cf03-4b50-8ebc-5db55e05438f)
text in compare section is not visible when dark mode is selected

also signup and login forms are not reflecting to dark mode changes 
![image](https://github.com/user-attachments/assets/15451717-7c46-4f4e-a9be-d26d437d8948)

assign this to me under gssoc-ext and hacktoberfest

**Comment by vanshchauhan21** [comment]
> ![image](https://private-user-images.githubusercontent.com/137872276/379734456-3dfaa54a-e361-44e8-8848-90ae41c4fcf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTY0NTksIm5iZiI6MTcyOTg1NjE1OSwicGF0aCI6Ii8xMzc4NzIyNzYvMzc5NzM0NDU2LTNkZmFhNTRhLWUzNjEtNDRlOC04ODQ4LTkwYWU0MWM0ZmNmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxMTM1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjFiM2ZkZmEzZmU4MGNhYmFkM2MxODFlODY1NWI0NDgxODViNjEwZjk4NmU5OTIwZWFiYzJjYjAwZTczZTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aycm4YBdcSExBda-nUCoNGxxNU-TwPwU6fA1EdsScKc) ![image](https://private-user-images.githubusercontent.com/137872276/379735520-bbf4108f-cf03-4b50-8ebc-5db55e05438f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTY0NTksIm5iZiI6MTcyOTg1NjE1OSwicGF0aCI6Ii8xMzc4NzIyNzYvMzc5NzM1NTIwLWJiZjQxMDhmLWNmMDMtNGI1MC04ZWJjLTVkYjU1ZTA1NDM4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxMTM1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTkwYTBiMDZhZjBiZjExZTdmZjU0ODIxNWE3NmViODMwM2RjYmIxMmVlYTNhNjFhZjc5OWMyZWNlZjZjZjYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZuTbeL-Sx_M4S11G-rY_DqhFrBVColZWZx54AoCgrmM) text in compare section is not visible when dark mode is selected
> 
> also signup and login forms are not reflecting to dark mode changes ![image](https://private-user-images.githubusercontent.com/137872276/379734521-15451717-7c46-4f4e-a9be-d26d437d8948.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTY0NTksIm5iZiI6MTcyOTg1NjE1OSwicGF0aCI6Ii8xMzc4NzIyNzYvMzc5NzM0NTIxLTE1NDUxNzE3LTdjNDYtNGY0ZS1hOWJlLWQyNmQ0MzdkODk0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxMTM1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjIxODM0Yzc3ODk5ZmFmNjRhMjQ2YjAxM2VkYzRlNWUxMmRhMmQzMDAyZWNkMWQ4MzJmMDM3MGVlZTRlYjQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OLNfMgjntKcPpk82seIl_XVbOL_caxIbXQ_N9fU2-1A)
> 
> assign this to me under gssoc-ext and hacktoberfest

Okay do it bro
