### ISSUE TITLE
Feature Request: Add Authentication Using Google/GitHub etc

### ISSUE THREAD

**Issue by amitb0ra** [vanshchauhan21/CryptoTracker#89]
We would like to implement **Social Authentication** in the CryptoTracker application, allowing users to sign up and log in using their existing Google or GitHub accounts (and potentially other providers). This will enhance user experience by simplifying the registration and login processes.

**Please assign me under GSSoC'24 ext and hacktoberfest labels**

**Comment by amitb0ra** [comment]
@vanshchauhan21 can i get a level 3 coz its a new feature from scratch?

**Comment by vanshchauhan21** [comment]
> @vanshchauhan21 can i get a level 3 coz its a new feature from scratch?

Oky dude

**Comment by amitb0ra** [comment]
> > @vanshchauhan21 can i get a level 3 coz its a new feature from scratch?
> 
> Oky dude

thanks! can you check PR too
