### ISSUE TITLE
 Feature Request: Price Alerts

### ISSUE THREAD

**Issue by amitb0ra** [vanshchauhan21/CryptoTracker#90]
We would like to implement a price alert feature in the CryptoTracker application. This feature will allow users to set alerts for specific cryptocurrencies, notifying them when the price reaches a predefined level.

**Please assign me under GSSoC'24 ext and hacktoberfest labels**

**Comment by vanshchauhan21** [comment]
> We would like to implement a price alert feature in the CryptoTracker application. This feature will allow users to set alerts for specific cryptocurrencies, notifying them when the price reaches a predefined level.
> 
> **Please assign me under GSSoC'24 ext and hacktoberfest labels**

Okay do it and all the best

**Comment by amitb0ra** [comment]
@vanshchauhan21 can you add level 3 label too?

**Comment by vanshchauhan21** [comment]
> @vanshchauhan21 can you add level 3 label too?

Done bro 👍
