### ISSUE TITLE
Feature Request: News Feed

### ISSUE THREAD

**Issue by amitb0ra** [vanshchauhan21/CryptoTracker#91]
We want to implement a News Feed feature in the CryptoTracker application that aggregates cryptocurrency news from various sources. This feature will allow users to stay informed about the latest developments in the crypto market.

**Please assign me under GSSoC'24 ext and hacktoberfest labels**

**Comment by vanshchauhan21** [comment]
> We want to implement a News Feed feature in the CryptoTracker application that aggregates cryptocurrency news from various sources. This feature will allow users to stay informed about the latest developments in the crypto market.
> 
> **Please assign me under GSSoC'24 ext and hacktoberfest labels**

Oky do it 😀all the best

**Comment by amitb0ra** [comment]
@vanshchauhan21 can you add level 3 label too?

**Comment by amitb0ra** [comment]
@vanshchauhan21 done :)
